/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Interfaz;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class FrmCalculadora extends javax.swing.JFrame {

    private int number1, number2, flag, result;
    private String signo, nString, auxNum;
    private boolean band;
    public FrmCalculadora() {
        initComponents();
        result = 0;//Esta variable contiene el resultado de la operacion
        band = false;//Variable para determinar si la variable number1 tiene almacenado un valor
        number1 = 0;//Numero 1 a operar
        number2 = 0;//Numero 2 a operar
        flag = 1;//Variable que lleva el control de la variable(number1/number2) en la que se almacenara el numero
        nString = "";//Numero con todo y signo que se mostrara en el interfaz
        auxNum = "";//Variable que almacena y junta el numero que se almacenara en la variable number1 o number2
        signo = "x";//Esta variable contiene la operacion que se va a realizar con los numeros
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBg = new javax.swing.JPanel();
        pnOne = new javax.swing.JPanel();
        lbOne = new javax.swing.JLabel();
        pnTwo = new javax.swing.JPanel();
        lbTwo = new javax.swing.JLabel();
        pnTree = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnFor = new javax.swing.JPanel();
        lbFor = new javax.swing.JLabel();
        pnFive = new javax.swing.JPanel();
        lbFive = new javax.swing.JLabel();
        pnSix = new javax.swing.JPanel();
        lbSix = new javax.swing.JLabel();
        pnSeven = new javax.swing.JPanel();
        lbSeven = new javax.swing.JLabel();
        pnOcho = new javax.swing.JPanel();
        lbOcho = new javax.swing.JLabel();
        pnNine = new javax.swing.JPanel();
        lbNine = new javax.swing.JLabel();
        pnExit = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        pnResult = new javax.swing.JPanel();
        lbResult = new javax.swing.JLabel();
        pnX = new javax.swing.JPanel();
        lbX = new javax.swing.JLabel();
        pnEnt = new javax.swing.JPanel();
        lbEnt = new javax.swing.JLabel();
        pnCero = new javax.swing.JPanel();
        lbCero = new javax.swing.JLabel();
        pnPunto = new javax.swing.JPanel();
        lbPunto = new javax.swing.JLabel();
        pnIgual = new javax.swing.JPanel();
        lbIgual = new javax.swing.JLabel();
        pnMenos = new javax.swing.JPanel();
        lbMenos = new javax.swing.JLabel();
        pnPlus = new javax.swing.JPanel();
        lbPlus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnBg.setBackground(new java.awt.Color(33, 33, 33));
        pnBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbOne.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOne.setText("1");
        lbOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbOneMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbOneMousePressed(evt);
            }
        });
        pnOne.add(lbOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnBg.add(pnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 30));

        lbTwo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTwo.setText("2");
        lbTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbTwoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnTwoLayout = new javax.swing.GroupLayout(pnTwo);
        pnTwo.setLayout(pnTwoLayout);
        pnTwoLayout.setHorizontalGroup(
            pnTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTwoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnTwoLayout.setVerticalGroup(
            pnTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTwoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnTreeLayout = new javax.swing.GroupLayout(pnTree);
        pnTree.setLayout(pnTreeLayout);
        pnTreeLayout.setHorizontalGroup(
            pnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTreeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnTreeLayout.setVerticalGroup(
            pnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTreeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 30));

        pnFor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFor.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFor.setText("4");
        lbFor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbForMousePressed(evt);
            }
        });
        pnFor.add(lbFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnBg.add(pnFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 30));

        lbFive.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFive.setText("5");
        lbFive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFiveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnFiveLayout = new javax.swing.GroupLayout(pnFive);
        pnFive.setLayout(pnFiveLayout);
        pnFiveLayout.setHorizontalGroup(
            pnFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnFiveLayout.setVerticalGroup(
            pnFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFiveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbFive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 30));

        lbSix.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSix.setText("6");
        lbSix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbSixMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnSixLayout = new javax.swing.GroupLayout(pnSix);
        pnSix.setLayout(pnSixLayout);
        pnSixLayout.setHorizontalGroup(
            pnSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSix, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnSixLayout.setVerticalGroup(
            pnSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSixLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbSix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 40, 30));

        pnSeven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnSeven.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSeven.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbSeven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSeven.setText("7");
        lbSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbSevenMousePressed(evt);
            }
        });
        pnSeven.add(lbSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnBg.add(pnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 40, 30));

        lbOcho.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbOcho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOcho.setText("8");
        lbOcho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbOchoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnOchoLayout = new javax.swing.GroupLayout(pnOcho);
        pnOcho.setLayout(pnOchoLayout);
        pnOchoLayout.setHorizontalGroup(
            pnOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbOcho, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnOchoLayout.setVerticalGroup(
            pnOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOchoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 40, 30));

        lbNine.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbNine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNine.setText("9");
        lbNine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbNineMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnNineLayout = new javax.swing.GroupLayout(pnNine);
        pnNine.setLayout(pnNineLayout);
        pnNineLayout.setHorizontalGroup(
            pnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnNineLayout.setVerticalGroup(
            pnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNineLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbNine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 40, 30));

        lbExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnExitLayout = new javax.swing.GroupLayout(pnExit);
        pnExit.setLayout(pnExitLayout);
        pnExitLayout.setHorizontalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnExitLayout.setVerticalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, 20));

        pnResult.setBackground(new java.awt.Color(102, 102, 102));

        lbResult.setBackground(new java.awt.Color(255, 255, 255));
        lbResult.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbResult.setText("0");

        javax.swing.GroupLayout pnResultLayout = new javax.swing.GroupLayout(pnResult);
        pnResult.setLayout(pnResultLayout);
        pnResultLayout.setHorizontalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResultLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnResultLayout.setVerticalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResultLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 50));

        pnX.setBackground(new java.awt.Color(255, 153, 0));

        lbX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbX.setText("x");
        lbX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnXLayout = new javax.swing.GroupLayout(pnX);
        pnX.setLayout(pnXLayout);
        pnXLayout.setHorizontalGroup(
            pnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbX, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnXLayout.setVerticalGroup(
            pnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnBg.add(pnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 30));

        pnEnt.setBackground(new java.awt.Color(255, 255, 0));
        pnEnt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbEnt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbEnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEnt.setText("ent");
        lbEnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnEnt.add(lbEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnBg.add(pnEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 40, 30));

        pnCero.setBackground(new java.awt.Color(244, 244, 244));

        lbCero.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbCero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCero.setText("0");
        lbCero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCeroMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnCeroLayout = new javax.swing.GroupLayout(pnCero);
        pnCero.setLayout(pnCeroLayout);
        pnCeroLayout.setHorizontalGroup(
            pnCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCero, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnCeroLayout.setVerticalGroup(
            pnCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCeroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbCero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, 30));

        pnPunto.setBackground(new java.awt.Color(255, 255, 0));

        lbPunto.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbPunto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPunto.setText(".");
        lbPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnPuntoLayout = new javax.swing.GroupLayout(pnPunto);
        pnPunto.setLayout(pnPuntoLayout);
        pnPuntoLayout.setHorizontalGroup(
            pnPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnPuntoLayout.setVerticalGroup(
            pnPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPuntoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 40, 30));

        pnIgual.setBackground(new java.awt.Color(255, 153, 0));

        lbIgual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIgual.setText("=");
        lbIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIgualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnIgualLayout = new javax.swing.GroupLayout(pnIgual);
        pnIgual.setLayout(pnIgualLayout);
        pnIgualLayout.setHorizontalGroup(
            pnIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnIgualLayout.setVerticalGroup(
            pnIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIgualLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, 30));

        pnMenos.setBackground(new java.awt.Color(255, 153, 0));

        lbMenos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbMenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenos.setText("-");
        lbMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMenosLayout = new javax.swing.GroupLayout(pnMenos);
        pnMenos.setLayout(pnMenosLayout);
        pnMenosLayout.setHorizontalGroup(
            pnMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnMenosLayout.setVerticalGroup(
            pnMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, 30));

        pnPlus.setBackground(new java.awt.Color(255, 153, 0));

        lbPlus.setBackground(new java.awt.Color(204, 204, 204));
        lbPlus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlus.setText("+");
        lbPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnPlusLayout = new javax.swing.GroupLayout(pnPlus);
        pnPlus.setLayout(pnPlusLayout);
        pnPlusLayout.setHorizontalGroup(
            pnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnPlusLayout.setVerticalGroup(
            pnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPlusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnBg.add(pnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 40, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("By created New King");
        pnBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void functionSigno(String sg){
        if(band == false){//Condicional para darle valor a la varibale number1 y nString en el caso de que el usuario no eliga valor para el numero 1 pero si para el numero 2(numero 1 y numero 2 son los numeros a operar)
                          //Es decir si el usuario decide continuar sus operaciones matematicas con el numero que le quedo como resultado de la anterior operacion
                number1 = result;
                nString = "" + result;
            }
        signo = sg;
        nString += signo;
        lbResult.setText(nString);
        auxNum = "";//Reiniciamos la variable nString para que se almacene el nuevo numero
        flag = 2;//Le damos valor 2 para que el numero que se escrbie el usuario se almacene en la variable NUMBER2
    }
    
    private void Operation(){
        switch(signo){
            case "+":
                result = number1 + number2;
                break;
            case "-":
                result = number1 - number2;
                break;
            case "x":
                result = number1 * number2;
                break;
            case "/":
                result = number1 / number2;
                break;
        }
        lbResult.setText("" + result);
    }
    
    private void printNumber(int n){
        auxNum += n;//Formamos el numero segun vallan presionando los numeros en la caluladora(interfaz)
        nString += n;//formamos el numero para imprimir en la interfaz de la calculadora
        
        if(flag == 1){
            number1 = Integer.parseInt(auxNum); 
            band = true;
        }
        else{            
            number2 = Integer.parseInt(auxNum);
        }
        lbResult.setText(nString);
    }
    
    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        pnExit.setBackground(Color.red);
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        pnExit.setBackground(Color.white);
    }//GEN-LAST:event_lbExitMouseExited

    //Me equivoque
    private void lbOneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbOneMouseEntered

    private void lbOneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOneMousePressed
        printNumber(1);
    }//GEN-LAST:event_lbOneMousePressed

    private void lbTwoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTwoMousePressed
        printNumber(2);
    }//GEN-LAST:event_lbTwoMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        printNumber(3);
    }//GEN-LAST:event_jLabel1MousePressed

    private void lbForMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForMousePressed
        printNumber(4);
    }//GEN-LAST:event_lbForMousePressed

    private void lbFiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFiveMousePressed
        printNumber(5);
    }//GEN-LAST:event_lbFiveMousePressed

    private void lbSixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSixMousePressed
        printNumber(6);
    }//GEN-LAST:event_lbSixMousePressed

    private void lbSevenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSevenMousePressed
        printNumber(7);
    }//GEN-LAST:event_lbSevenMousePressed

    private void lbOchoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOchoMousePressed
        printNumber(8);
    }//GEN-LAST:event_lbOchoMousePressed

    private void lbNineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNineMousePressed
        printNumber(9);
    }//GEN-LAST:event_lbNineMousePressed

    private void lbCeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCeroMousePressed
        printNumber(0);
    }//GEN-LAST:event_lbCeroMousePressed

    private void lbPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlusMouseClicked
        functionSigno("+");
    }//GEN-LAST:event_lbPlusMouseClicked

    private void lbIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIgualMouseClicked
        Operation();
        nString = "";//Reiniciamos la variable nString para que se almacene el nuevo numero
        auxNum = "";//Reiniciamos la variable nString para que se almacene el nuevo numero
        flag = 1;//Le damos  valor 1 para que el numero que escribe el usuario se almacene en la variable NUMBER1
        band = false;
    }//GEN-LAST:event_lbIgualMouseClicked

    private void lbXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXMouseClicked
        functionSigno("x");
    }//GEN-LAST:event_lbXMouseClicked

    private void lbMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenosMouseClicked
        functionSigno("-");
    }//GEN-LAST:event_lbMenosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbCero;
    private javax.swing.JLabel lbEnt;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbFive;
    private javax.swing.JLabel lbFor;
    private javax.swing.JLabel lbIgual;
    private javax.swing.JLabel lbMenos;
    private javax.swing.JLabel lbNine;
    private javax.swing.JLabel lbOcho;
    private javax.swing.JLabel lbOne;
    private javax.swing.JLabel lbPlus;
    private javax.swing.JLabel lbPunto;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSeven;
    private javax.swing.JLabel lbSix;
    private javax.swing.JLabel lbTwo;
    private javax.swing.JLabel lbX;
    private javax.swing.JPanel pnBg;
    private javax.swing.JPanel pnCero;
    private javax.swing.JPanel pnEnt;
    private javax.swing.JPanel pnExit;
    private javax.swing.JPanel pnFive;
    private javax.swing.JPanel pnFor;
    private javax.swing.JPanel pnIgual;
    private javax.swing.JPanel pnMenos;
    private javax.swing.JPanel pnNine;
    private javax.swing.JPanel pnOcho;
    private javax.swing.JPanel pnOne;
    private javax.swing.JPanel pnPlus;
    private javax.swing.JPanel pnPunto;
    private javax.swing.JPanel pnResult;
    private javax.swing.JPanel pnSeven;
    private javax.swing.JPanel pnSix;
    private javax.swing.JPanel pnTree;
    private javax.swing.JPanel pnTwo;
    private javax.swing.JPanel pnX;
    // End of variables declaration//GEN-END:variables
}
